
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_CLOSURE_HEADER" ("HEADER_ID", "CLOSURE_DATE", "CLOSURE_MONTH", "CLOSURE_YEAR", "USER_NAME", "STATUS") AS 
  SELECT
  ch.HEADER_ID,
  ch.CLOSURE_DATE,
  ch.CLOSURE_MONTH,
  ch.CLOSURE_YEAR,
  u.NAME AS USER_NAME,
  ch.STATUS
FROM CLOSURE_HEADER ch
LEFT JOIN USERS u ON ch.USER_ID = u.USER_ID
ORDER BY ch.CLOSURE_DATE DESC;

