
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_CLOSURE_DETAILS" ("CLOSURE_ID", "HEADER_ID", "PRODUCT_NAME", "LOT_ID", "FINAL_STOCK", "CLOSURE_DATE") AS 
  SELECT 
    ic.CLOSURE_ID,
    ic.HEADER_ID,
    p.PRODUCT_NAME,
    l.LOT_ID,
    ic.FINAL_STOCK,
    ic.CLOSURE_DATE
FROM INVENTORY_CLOSURE ic
JOIN PRODUCTS p ON ic.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN BATCHES l ON ic.LOT_ID = l.LOT_ID
ORDER BY ic.HEADER_ID, p.PRODUCT_NAME;

