-- Vista para el Reporte de Ingresos por Lote
-- Historia de Usuario: GES-168
-- Descripción: Ingresos por lote para conocer cuándo y qué productos entraron

CREATE OR REPLACE VIEW VW_INCOME_BY_LOT AS
SELECT 
    b.LOT_ID,
    b.RFID_CODE AS LOT_CODE,
    b.DESCRIPTION AS LOT_DESCRIPTION,
    b.ENTRY_DATE,
    p.PRODUCT_ID,
    p.PRODUCT_CODE,
    p.PRODUCT_NAME,
    pc.CATEGORY_NAME,
    mt.MEASUREMENT_NAME,
    i.ACTUAL_STOCK AS CURRENT_UNITS,
    p.UNIT_PRICE,
    (i.ACTUAL_STOCK * p.UNIT_PRICE) AS TOTAL_VALUE,
    ps.STATE_NAME AS PRODUCT_STATE,
    i.UPDATED_AT AS LAST_UPDATE
FROM 
    BATCHES b
    INNER JOIN INVENTORY i ON b.LOT_ID = i.LOT_ID
    INNER JOIN PRODUCTS p ON i.PRODUCT_ID = p.PRODUCT_ID
    INNER JOIN PRODUCT_CATEGORIES pc ON p.CATEGORY_ID = pc.CATEGORY_ID
    INNER JOIN PRODUCT_STATES ps ON p.STATE_ID = ps.STATE_ID
    INNER JOIN MEASUREMENTS_TYPES mt ON p.MEASUREMENT_ID = mt.MEASUREMENT_ID
WHERE 
    ps.STATE_ID = 1  -- Solo productos activos
ORDER BY 
    b.ENTRY_DATE DESC,
    pc.CATEGORY_NAME ASC,
    p.PRODUCT_NAME ASC;
