
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_INVENTORY_CLOSURE_DETAILS" ("CLOSURE_ID", "CLOSURE_DATE", "FINAL_STOCK", "LOT_ID", "PRODUCT_NAME", "USER_NAME", "HEADER_ID") AS 
  SELECT 
    IC.CLOSURE_ID,
    IC.CLOSURE_DATE,
    IC.FINAL_STOCK,
    IC.LOT_ID,
    P.PRODUCT_NAME,
    U.NAME AS USER_NAME,
    IC.HEADER_ID
FROM GESTOCK.INVENTORY_CLOSURE IC
LEFT JOIN GESTOCK.PRODUCTS P
    ON IC.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN GESTOCK.USERS U
    ON IC.USER_ID = U.USER_ID
LEFT JOIN GESTOCK.CLOSURE_HEADER CH
    ON IC.HEADER_ID = CH.HEADER_ID;

