
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_INVENTORY_DETAIL" ("CODIGO_PRODUCTO", "NOMBRE_PRODUCTO", "DESCRIPCION_PRODUCTO", "CATEGORIA_PRODUCTO", "STOCK_ACTUAL", "STOCK_MINIMO", "PRECIO_UNITARIO", "ESTADO_PRODUCTO", "LOT_ID", "TIPO_MEDIDA") AS 
  SELECT 
    PR.PRODUCT_CODE AS CODIGO_PRODUCTO,
    PR.PRODUCT_NAME AS NOMBRE_PRODUCTO,
    PR.PRODUCT_DESCRIPTION AS DESCRIPCION_PRODUCTO,
    CT.CATEGORY_NAME AS CATEGORIA_PRODUCTO,
    INV.ACTUAL_STOCK AS STOCK_ACTUAL,
    INV.MINIMUM_STOCK AS STOCK_MINIMO,
    PR.UNIT_PRICE AS PRECIO_UNITARIO,
    ST.STATE_NAME AS ESTADO_PRODUCTO,
    INV.LOT_ID AS LOT_ID,
    MT.MEASUREMENT_NAME AS TIPO_MEDIDA
FROM INVENTORY INV
JOIN PRODUCTS PR ON INV.PRODUCT_ID = PR.PRODUCT_ID
JOIN PRODUCT_CATEGORIES CT ON PR.CATEGORY_ID = CT.CATEGORY_ID
JOIN PRODUCT_STATES ST ON PR.STATE_ID = ST.STATE_ID
JOIN MEASUREMENTS_TYPES MT ON PR.MEASUREMENT_ID = MT.MEASUREMENT_ID;

