-- Vista para el Reporte General de Inventario
-- Historia de Usuario: GES-166
-- Descripción: Unidades disponibles por producto

CREATE OR REPLACE VIEW VW_INVENTORY_REPORT AS
SELECT 
    p.PRODUCT_ID,
    p.PRODUCT_CODE,
    p.PRODUCT_NAME,
    p.PRODUCT_DESCRIPTION,
    pc.CATEGORY_NAME,
    ps.STATE_NAME AS PRODUCT_STATE,
    mt.MEASUREMENT_NAME,
    i.ACTUAL_STOCK AS AVAILABLE_UNITS,
    i.MINIMUM_STOCK,
    p.UNIT_PRICE,
    (i.ACTUAL_STOCK * p.UNIT_PRICE) AS TOTAL_VALUE,
    CAST(i.LOT_ID AS VARCHAR2(50)) AS LOT_CODE,
    i.UPDATED_AT AS LAST_UPDATE
FROM 
    PRODUCTS p
    INNER JOIN INVENTORY i ON p.PRODUCT_ID = i.PRODUCT_ID
    INNER JOIN PRODUCT_CATEGORIES pc ON p.CATEGORY_ID = pc.CATEGORY_ID
    INNER JOIN PRODUCT_STATES ps ON p.STATE_ID = ps.STATE_ID
    INNER JOIN MEASUREMENTS_TYPES mt ON p.MEASUREMENT_ID = mt.MEASUREMENT_ID
WHERE 
    ps.STATE_ID = 1  -- Solo productos activos
ORDER BY 
    pc.CATEGORY_NAME ASC,
    p.PRODUCT_NAME ASC;
